let book, current = 0;
const $ = s => document.querySelector(s);
fetch('book.json').then(r => r.json()).then(b => { book = b; buildToc(); render(0); });
function buildToc() { book.chapters.forEach((c, i) => { const a = document.createElement('a'); a.href = '#' + c.id; a.textContent = zhTitle(c.title); a.onclick = e => { e.preventDefault(); render(i); document.querySelector('aside').classList.remove('open'); }; a.id = 'toc-' + i; $('#toc').append(a); }); }
function zhTitle(t) { return ({Preface:'序言', Introduction:'引言', Appendix:'附录', Notes:'注释', Acknowledgments:'致谢'})[t] || t; }
function inline(s) { return esc(s).replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>').replace(/__(.+?)__/g, '<strong>$1</strong>').replace(/\*([^*]+?)\*/g, '<em>$1</em>').replace(/_([^_]+?)_/g, '<em>$1</em>'); }
function renderMarkdown(markdown) { const lines = markdown.split(/\n/); let html = '', table = []; const flush = () => { if (table.length) { html += '<table><tbody>' + table.join('') + '</tbody></table>'; table = []; } }; for (const line of lines) { if (line.trim().startsWith('|')) { const cells = line.trim().split('|').slice(1, -1).map(v => v.trim()); if (!cells.every(v => /^[-: ]+$/.test(v))) table.push('<tr>' + cells.map(v => '<td>' + inline(v) + '</td>').join('') + '</tr>'); continue; } flush(); if (!line.trim()) continue; if (line.startsWith('### ')) html += '<h4>' + inline(line.slice(4)) + '</h4>'; else if (line.startsWith('## ')) html += '<h3>' + inline(line.slice(3)) + '</h3>'; else if (line.startsWith('# ')) html += '<h2>' + inline(line.slice(2)) + '</h2>'; else if (line.startsWith('> ')) html += '<blockquote>' + inline(line.slice(2)) + '</blockquote>'; else if (/^[-*] /.test(line)) html += '<li>' + inline(line.slice(2)) + '</li>'; else html += '<p>' + inline(line) + '</p>'; } flush(); return html; }
async function render(i) { current = i; const c = book.chapters[i]; let translated = ''; try { const r = await fetch(c.id + '.zh.md'); if (r.ok) translated = await r.text(); } catch (e) {} let body = translated ? renderMarkdown(translated) : c.blocks.map(b => b.type === 'heading' ? '<h3>' + inline(b.text) + '</h3>' : '<p>' + inline(b.text) + '</p>').join(''); if (c.id === 'intro') body = '<figure><img src="assets/Figure01_fmt.jpeg" alt="作者投资组合表现图"><figcaption>作者投资组合表现图（原书插图）</figcaption></figure>' + body; if (c.id === 'chapter6') body += '<figure><img src="assets/Figure02_fmt.jpeg" alt="原书图表"><figcaption>原书图表</figcaption></figure>'; $('#reader').innerHTML = body; document.querySelectorAll('nav a').forEach((a, j) => a.classList.toggle('active', j === i)); $('#progress').textContent = (i + 1) + ' / ' + book.chapters.length; history.replaceState(null, '', '#' + c.id); window.scrollTo({top: 0, behavior: 'smooth'}); }
function esc(s) { return s.replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])); }
$('#prev').onclick = () => render(Math.max(0, current - 1)); $('#next').onclick = () => render(Math.min(book.chapters.length - 1, current + 1)); $('#theme').onclick = () => document.body.classList.toggle('eye'); $('#menu').onclick = () => document.querySelector('aside').classList.toggle('open'); $('#size').oninput = e => $('#reader').style.fontSize = e.target.value + 'px';
